// 设置导航
export const SETTING__SET_ASIDE_NAV = 'SETTING__SET_ASIDE_NAV'
// 设置网络状态
export const SETTING__SET_NETWORK_STATUS = 'SETTING__SET_NETWORK_STATUS'

// 设置用户信息
export const USER__SET_USER_INFO = 'USER__SET_USER_INFO'
